#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sale_Book
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sale_book")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNha_xuat_ban(Nha_xuat_ban instance);
    partial void UpdateNha_xuat_ban(Nha_xuat_ban instance);
    partial void DeleteNha_xuat_ban(Nha_xuat_ban instance);
    partial void InsertSach(Sach instance);
    partial void UpdateSach(Sach instance);
    partial void DeleteSach(Sach instance);
    partial void InsertTac_gia(Tac_gia instance);
    partial void UpdateTac_gia(Tac_gia instance);
    partial void DeleteTac_gia(Tac_gia instance);
    partial void InsertThe_loai(The_loai instance);
    partial void UpdateThe_loai(The_loai instance);
    partial void DeleteThe_loai(The_loai instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["Sale_bookConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Chi_tiet> Chi_tiets
		{
			get
			{
				return this.GetTable<Chi_tiet>();
			}
		}
		
		public System.Data.Linq.Table<Nha_xuat_ban> Nha_xuat_bans
		{
			get
			{
				return this.GetTable<Nha_xuat_ban>();
			}
		}
		
		public System.Data.Linq.Table<Sach> Saches
		{
			get
			{
				return this.GetTable<Sach>();
			}
		}
		
		public System.Data.Linq.Table<Tac_gia> Tac_gias
		{
			get
			{
				return this.GetTable<Tac_gia>();
			}
		}
		
		public System.Data.Linq.Table<The_loai> The_loais
		{
			get
			{
				return this.GetTable<The_loai>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Chi_tiet")]
	public partial class Chi_tiet
	{
		
		private string _Hinh_anh;
		
		private string _Tom_tat_noi_dung;
		
		private System.Nullable<System.DateTime> _Nam_xuat_ban;
		
		private string _Ma_sach;
		
		public Chi_tiet()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh_anh", DbType="NVarChar(100)")]
		public string Hinh_anh
		{
			get
			{
				return this._Hinh_anh;
			}
			set
			{
				if ((this._Hinh_anh != value))
				{
					this._Hinh_anh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tom_tat_noi_dung", DbType="NVarChar(MAX)")]
		public string Tom_tat_noi_dung
		{
			get
			{
				return this._Tom_tat_noi_dung;
			}
			set
			{
				if ((this._Tom_tat_noi_dung != value))
				{
					this._Tom_tat_noi_dung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nam_xuat_ban", DbType="Date")]
		public System.Nullable<System.DateTime> Nam_xuat_ban
		{
			get
			{
				return this._Nam_xuat_ban;
			}
			set
			{
				if ((this._Nam_xuat_ban != value))
				{
					this._Nam_xuat_ban = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_sach", DbType="NVarChar(50)")]
		public string Ma_sach
		{
			get
			{
				return this._Ma_sach;
			}
			set
			{
				if ((this._Ma_sach != value))
				{
					this._Ma_sach = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nha_xuat_ban")]
	public partial class Nha_xuat_ban : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_nha_xuat_ban;
		
		private string _Ten_nha_xuat_ban;
		
		private EntitySet<Sach> _Saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_nha_xuat_banChanging(string value);
    partial void OnMa_nha_xuat_banChanged();
    partial void OnTen_nha_xuat_banChanging(string value);
    partial void OnTen_nha_xuat_banChanged();
    #endregion
		
		public Nha_xuat_ban()
		{
			this._Saches = new EntitySet<Sach>(new Action<Sach>(this.attach_Saches), new Action<Sach>(this.detach_Saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_nha_xuat_ban", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_nha_xuat_ban
		{
			get
			{
				return this._Ma_nha_xuat_ban;
			}
			set
			{
				if ((this._Ma_nha_xuat_ban != value))
				{
					this.OnMa_nha_xuat_banChanging(value);
					this.SendPropertyChanging();
					this._Ma_nha_xuat_ban = value;
					this.SendPropertyChanged("Ma_nha_xuat_ban");
					this.OnMa_nha_xuat_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_nha_xuat_ban", DbType="NVarChar(100)")]
		public string Ten_nha_xuat_ban
		{
			get
			{
				return this._Ten_nha_xuat_ban;
			}
			set
			{
				if ((this._Ten_nha_xuat_ban != value))
				{
					this.OnTen_nha_xuat_banChanging(value);
					this.SendPropertyChanging();
					this._Ten_nha_xuat_ban = value;
					this.SendPropertyChanged("Ten_nha_xuat_ban");
					this.OnTen_nha_xuat_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nha_xuat_ban_Sach", Storage="_Saches", ThisKey="Ma_nha_xuat_ban", OtherKey="Ma_nha_xuat_ban")]
		public EntitySet<Sach> Saches
		{
			get
			{
				return this._Saches;
			}
			set
			{
				this._Saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.Nha_xuat_ban = this;
		}
		
		private void detach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.Nha_xuat_ban = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sach")]
	public partial class Sach : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_sach;
		
		private string _Ten_sach;
		
		private System.Nullable<int> _So_luong_ton;
		
		private string _Ma_the_loai;
		
		private string _Ma_tac_gia;
		
		private string _Ma_nha_xuat_ban;
		
		private EntityRef<Nha_xuat_ban> _Nha_xuat_ban;
		
		private EntityRef<Tac_gia> _Tac_gia;
		
		private EntityRef<The_loai> _The_loai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_sachChanging(string value);
    partial void OnMa_sachChanged();
    partial void OnTen_sachChanging(string value);
    partial void OnTen_sachChanged();
    partial void OnSo_luong_tonChanging(System.Nullable<int> value);
    partial void OnSo_luong_tonChanged();
    partial void OnMa_the_loaiChanging(string value);
    partial void OnMa_the_loaiChanged();
    partial void OnMa_tac_giaChanging(string value);
    partial void OnMa_tac_giaChanged();
    partial void OnMa_nha_xuat_banChanging(string value);
    partial void OnMa_nha_xuat_banChanged();
    #endregion
		
		public Sach()
		{
			this._Nha_xuat_ban = default(EntityRef<Nha_xuat_ban>);
			this._Tac_gia = default(EntityRef<Tac_gia>);
			this._The_loai = default(EntityRef<The_loai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_sach", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_sach
		{
			get
			{
				return this._Ma_sach;
			}
			set
			{
				if ((this._Ma_sach != value))
				{
					this.OnMa_sachChanging(value);
					this.SendPropertyChanging();
					this._Ma_sach = value;
					this.SendPropertyChanged("Ma_sach");
					this.OnMa_sachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_sach", DbType="NVarChar(200)")]
		public string Ten_sach
		{
			get
			{
				return this._Ten_sach;
			}
			set
			{
				if ((this._Ten_sach != value))
				{
					this.OnTen_sachChanging(value);
					this.SendPropertyChanging();
					this._Ten_sach = value;
					this.SendPropertyChanged("Ten_sach");
					this.OnTen_sachChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_luong_ton", DbType="Int")]
		public System.Nullable<int> So_luong_ton
		{
			get
			{
				return this._So_luong_ton;
			}
			set
			{
				if ((this._So_luong_ton != value))
				{
					this.OnSo_luong_tonChanging(value);
					this.SendPropertyChanging();
					this._So_luong_ton = value;
					this.SendPropertyChanged("So_luong_ton");
					this.OnSo_luong_tonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_the_loai", DbType="NVarChar(50)")]
		public string Ma_the_loai
		{
			get
			{
				return this._Ma_the_loai;
			}
			set
			{
				if ((this._Ma_the_loai != value))
				{
					if (this._The_loai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_the_loaiChanging(value);
					this.SendPropertyChanging();
					this._Ma_the_loai = value;
					this.SendPropertyChanged("Ma_the_loai");
					this.OnMa_the_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_tac_gia", DbType="NVarChar(50)")]
		public string Ma_tac_gia
		{
			get
			{
				return this._Ma_tac_gia;
			}
			set
			{
				if ((this._Ma_tac_gia != value))
				{
					if (this._Tac_gia.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_tac_giaChanging(value);
					this.SendPropertyChanging();
					this._Ma_tac_gia = value;
					this.SendPropertyChanged("Ma_tac_gia");
					this.OnMa_tac_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_nha_xuat_ban", DbType="NVarChar(50)")]
		public string Ma_nha_xuat_ban
		{
			get
			{
				return this._Ma_nha_xuat_ban;
			}
			set
			{
				if ((this._Ma_nha_xuat_ban != value))
				{
					if (this._Nha_xuat_ban.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_nha_xuat_banChanging(value);
					this.SendPropertyChanging();
					this._Ma_nha_xuat_ban = value;
					this.SendPropertyChanged("Ma_nha_xuat_ban");
					this.OnMa_nha_xuat_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nha_xuat_ban_Sach", Storage="_Nha_xuat_ban", ThisKey="Ma_nha_xuat_ban", OtherKey="Ma_nha_xuat_ban", IsForeignKey=true)]
		public Nha_xuat_ban Nha_xuat_ban
		{
			get
			{
				return this._Nha_xuat_ban.Entity;
			}
			set
			{
				Nha_xuat_ban previousValue = this._Nha_xuat_ban.Entity;
				if (((previousValue != value) 
							|| (this._Nha_xuat_ban.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nha_xuat_ban.Entity = null;
						previousValue.Saches.Remove(this);
					}
					this._Nha_xuat_ban.Entity = value;
					if ((value != null))
					{
						value.Saches.Add(this);
						this._Ma_nha_xuat_ban = value.Ma_nha_xuat_ban;
					}
					else
					{
						this._Ma_nha_xuat_ban = default(string);
					}
					this.SendPropertyChanged("Nha_xuat_ban");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tac_gia_Sach", Storage="_Tac_gia", ThisKey="Ma_tac_gia", OtherKey="Ma_tac_gia", IsForeignKey=true)]
		public Tac_gia Tac_gia
		{
			get
			{
				return this._Tac_gia.Entity;
			}
			set
			{
				Tac_gia previousValue = this._Tac_gia.Entity;
				if (((previousValue != value) 
							|| (this._Tac_gia.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tac_gia.Entity = null;
						previousValue.Saches.Remove(this);
					}
					this._Tac_gia.Entity = value;
					if ((value != null))
					{
						value.Saches.Add(this);
						this._Ma_tac_gia = value.Ma_tac_gia;
					}
					else
					{
						this._Ma_tac_gia = default(string);
					}
					this.SendPropertyChanged("Tac_gia");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="The_loai_Sach", Storage="_The_loai", ThisKey="Ma_the_loai", OtherKey="Ma_the_loai", IsForeignKey=true)]
		public The_loai The_loai
		{
			get
			{
				return this._The_loai.Entity;
			}
			set
			{
				The_loai previousValue = this._The_loai.Entity;
				if (((previousValue != value) 
							|| (this._The_loai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._The_loai.Entity = null;
						previousValue.Saches.Remove(this);
					}
					this._The_loai.Entity = value;
					if ((value != null))
					{
						value.Saches.Add(this);
						this._Ma_the_loai = value.Ma_the_loai;
					}
					else
					{
						this._Ma_the_loai = default(string);
					}
					this.SendPropertyChanged("The_loai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tac_gia")]
	public partial class Tac_gia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_tac_gia;
		
		private string _Ten_tac_gia;
		
		private EntitySet<Sach> _Saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_tac_giaChanging(string value);
    partial void OnMa_tac_giaChanged();
    partial void OnTen_tac_giaChanging(string value);
    partial void OnTen_tac_giaChanged();
    #endregion
		
		public Tac_gia()
		{
			this._Saches = new EntitySet<Sach>(new Action<Sach>(this.attach_Saches), new Action<Sach>(this.detach_Saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_tac_gia", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_tac_gia
		{
			get
			{
				return this._Ma_tac_gia;
			}
			set
			{
				if ((this._Ma_tac_gia != value))
				{
					this.OnMa_tac_giaChanging(value);
					this.SendPropertyChanging();
					this._Ma_tac_gia = value;
					this.SendPropertyChanged("Ma_tac_gia");
					this.OnMa_tac_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_tac_gia", DbType="NVarChar(100)")]
		public string Ten_tac_gia
		{
			get
			{
				return this._Ten_tac_gia;
			}
			set
			{
				if ((this._Ten_tac_gia != value))
				{
					this.OnTen_tac_giaChanging(value);
					this.SendPropertyChanging();
					this._Ten_tac_gia = value;
					this.SendPropertyChanged("Ten_tac_gia");
					this.OnTen_tac_giaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tac_gia_Sach", Storage="_Saches", ThisKey="Ma_tac_gia", OtherKey="Ma_tac_gia")]
		public EntitySet<Sach> Saches
		{
			get
			{
				return this._Saches;
			}
			set
			{
				this._Saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.Tac_gia = this;
		}
		
		private void detach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.Tac_gia = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.The_loai")]
	public partial class The_loai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_the_loai;
		
		private string _Ten_the_loai;
		
		private EntitySet<Sach> _Saches;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_the_loaiChanging(string value);
    partial void OnMa_the_loaiChanged();
    partial void OnTen_the_loaiChanging(string value);
    partial void OnTen_the_loaiChanged();
    #endregion
		
		public The_loai()
		{
			this._Saches = new EntitySet<Sach>(new Action<Sach>(this.attach_Saches), new Action<Sach>(this.detach_Saches));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_the_loai", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_the_loai
		{
			get
			{
				return this._Ma_the_loai;
			}
			set
			{
				if ((this._Ma_the_loai != value))
				{
					this.OnMa_the_loaiChanging(value);
					this.SendPropertyChanging();
					this._Ma_the_loai = value;
					this.SendPropertyChanged("Ma_the_loai");
					this.OnMa_the_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_the_loai", DbType="NVarChar(200)")]
		public string Ten_the_loai
		{
			get
			{
				return this._Ten_the_loai;
			}
			set
			{
				if ((this._Ten_the_loai != value))
				{
					this.OnTen_the_loaiChanging(value);
					this.SendPropertyChanging();
					this._Ten_the_loai = value;
					this.SendPropertyChanged("Ten_the_loai");
					this.OnTen_the_loaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="The_loai_Sach", Storage="_Saches", ThisKey="Ma_the_loai", OtherKey="Ma_the_loai")]
		public EntitySet<Sach> Saches
		{
			get
			{
				return this._Saches;
			}
			set
			{
				this._Saches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.The_loai = this;
		}
		
		private void detach_Saches(Sach entity)
		{
			this.SendPropertyChanging();
			entity.The_loai = null;
		}
	}
}
#pragma warning restore 1591
